name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv bits_env
        source bits_env/bin/activate
        pip install -r requirements.txt

    - name: Print working directory
      run: pwd

    - name: Verify Data File
      run: |
        if [ -f "../data/diabetes.csv" ]; then echo "File exists"; else echo "File does not exist"; fi

    - name: Train ML Model
      run: |
        source bits_env/bin/activate
        cd /home/runner/work/MLops-end2end/MLops-end2end
        python src/train.py
        