name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  train:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv bits_env
        source bits_env/bin/activate
        pip install -r requirements.txt

    - name: Train ML Model
      run: |
        source bits_env/bin/activate
        python src/train.py  # Adjust this command based on your training script
      